# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('cost', models.FloatField(blank=True, default=0)),
                ('time', models.DateTimeField(null=True)),
                ('rate', models.FloatField(blank=True, default=0)),
                ('message', models.TextField()),
                ('location', models.TextField()),
                ('destination', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='client.Client')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='driver.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='order.Order')),
            ],
        ),
    ]
